version: "3"
services:
  web:
    build:
      dockerfile: ./app.dockerfile
      context: .
    ports:
      - "4000:4000"
    command: >
      bash -c "mix ecto.create && mix ecto.migrate && iex -S mix phx.server"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=db
    networks:
      - custom-network
    depends_on:
      - db
  db:
    image: postgres:9.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./.pgdata:/var/lib/postgresql/data"
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
